package application;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

public class ThneedMainWindowController {
	@FXML
	private Button newOrderButton;
	@FXML
	private TextField listField;
	@FXML
	private TextField currentField;
	@FXML
	private Button custInfoButton;
	@FXML
	private Button saveButton;
	@FXML
	private Button newCustButton;
	@FXML
	private Button editDateButton;

	public ArrayList<Order> thneedOrders;
	
	
	@FXML
	public void initialize() {
		loadOrders();
		System.out.println("Works here too");
	}

	// Event Listener on Button[#newOrderButton].onAction
	@FXML
	public void newOrderClick(ActionEvent event) {
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/ThneedNewOrderWindow.fxml"));
		AnchorPane dialogRoot;
		//try except to get the new window to show
		try {
			dialogRoot = (AnchorPane) loader.load();
			Scene dialogScene = new Scene(dialogRoot);
			Stage dialogStage = new Stage();
			dialogStage.setScene(dialogScene);
			ThneedNewOrderWindowController dialogController = (ThneedNewOrderWindowController) loader.getController();
			dialogStage.show();
			System.out.println("After dialogStage.show()");
			
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#custInfoButton].onAction
	@FXML
	public void newCustClick(ActionEvent event) {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/ThneedNewCustomerWindow.fxml"));
		AnchorPane dialogRoot;
		//try except to ge the new window to show
		try {
			dialogRoot = (AnchorPane) loader.load();
			Scene dialogScene = new Scene(dialogRoot);
			Stage dialogStage = new Stage();
			dialogStage.setScene(dialogScene);
			ThneedNewCustomerWindowController dialogController = (ThneedNewCustomerWindowController) loader.getController();
			dialogStage.show();
			System.out.println("After dialogStage.show()");
			
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	// Event Listener on Button[#saveButton].onAction
	@FXML
	public void saveButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#newCustButton].onAction
	@FXML
	public void viewCustomerClick(ActionEvent event) {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/ThneedViewCustomerWindow.fxml"));
		AnchorPane dialogRoot;
		//try except to get the new window to show
		try {
			dialogRoot = (AnchorPane) loader.load();
			Scene dialogScene = new Scene(dialogRoot);
			Stage dialogStage = new Stage();
			dialogStage.setScene(dialogScene);
			ThneedViewCustomerWindowController dialogController = (ThneedViewCustomerWindowController) loader.getController();
			dialogStage.show();
			System.out.println("After dialogStage.show()");
			
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	// Event Listener on Button[#editDateButton].onAction
	@FXML
	public void editDateClick(ActionEvent event) {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/ThneedEditDateWindow.fxml"));
		AnchorPane dialogRoot;
		//try except to get the new window to show
		try {
			dialogRoot = (AnchorPane) loader.load();
			Scene dialogScene = new Scene(dialogRoot);
			Stage dialogStage = new Stage();
			dialogStage.setScene(dialogScene);
			ThneedEditDateWindowController dialogController = (ThneedEditDateWindowController) loader.getController();
			dialogStage.show();
			System.out.println("After dialogStage.show()");
			
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	public void loadOrders() {
		System.out.println("Working");
		List<Order> orders = FileIO.loadOrders();
		String orderList = "";
		for (int i = 0; i < orders.size(); i++) {
			Order order = orders.get(i);
			orderList += "Order Number: " + order.getorderNumber() + ", ";
			orderList += "Customer: " + order.getCustomer().getName() + ", ";
			orderList += "Order Date: " + formatDate(order.getDateOrdered()) + ", ";
			orderList += "Date Filled: " + formatDate(order.getDateFilled()) + "\n";
			System.out.println("1" + orderList);
		}
		System.out.println(orderList);
	}
	
	private static String formatDate(Date date) {
		SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        return dateFormat.format(date);
	}
}
