package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class ThneedNewCustomerWindowController {
	@FXML
	private TextField customerNameField;
	@FXML
	private TextField customerAddressField;
	@FXML
	private TextField customerPhoneNumField;
	@FXML
	private Button customerSubmitButton;
	@FXML
	private Button customerCancelButton;

	// Event Listener on Button[#customerSubmitButton].onAction
	@FXML
	public void customerSubmitButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#customerCancelButton].onAction
	@FXML
	public void customerCancelButtonClick(ActionEvent event) {
		customerNameField.clear();
		customerAddressField.clear();
		customerPhoneNumField.clear();
	}
}
