package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;

import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

public class ThneedNewOrderWindowController {
	@FXML
	private Button cancelOrderButton;
	@FXML
	private TextField orderQuantityField;
	@FXML
	private TextField orderCustomerNameField;
	@FXML
	private TextField orderDatePlacedField;
	@FXML
	private TextField orderDateFilledField;
	@FXML
	private Button submitOrderButton;
	@FXML
	private RadioButton pinkThneedButton;
	@FXML
	private ToggleGroup thneedColorGroup;
	@FXML
	private RadioButton orangeThneedButton;
	@FXML
	private RadioButton yellowThneedButton;
	@FXML
	private RadioButton smallThneedButton;
	@FXML
	private RadioButton mediumThneedButton;
	@FXML
	private RadioButton largeThneedButton;
	@FXML
	private RadioButton XLThneedButton;
	@FXML
	private RadioButton greenThneedButton;
	@FXML
	private RadioButton purpleThneedButton;

	// Event Listener on Button[#cancelOrderButton].onAction
	@FXML
	public void cancelOrderButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#submitOrderButton].onAction
	@FXML
	public void submitOrderButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
