package application;

import java.util.ArrayList;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class ThneedMainWindowController {
	@FXML
	private Button newOrderButton;
	@FXML
	private TextField listField;
	@FXML
	private TextField currentField;
	@FXML
	private Button custInfoButton;
	@FXML
	private Button saveButton;
	@FXML
	private Button newCustButton;
	@FXML
	private Button editDateButton;

	public ArrayList<Order> thneedOrders;

	// Event Listener on Button[#newOrderButton].onAction
	@FXML
	public void newOrderClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#custInfoButton].onAction
	@FXML
	public void viewCustomerClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#saveButton].onAction
	@FXML
	public void saveButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#newCustButton].onAction
	@FXML
	public void newCustClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#editDateButton].onAction
	@FXML
	public void editDateClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
