package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

public class ThneedEditDateWindowController {
	@FXML
	private TextField changeDateFilledField;
	@FXML
	private TextArea changeDateOrderInfoField;
	@FXML
	private Button updateDateButton;
	@FXML
	private Button updateDateCancelButton;

	// Event Listener on Button[#updateDateButton].onAction
	@FXML
	public void updateDateButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateDateCancelButton].onAction
	@FXML
	public void updateDateCancelButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
